workflows:
  clearmind-ios:
    name: ClearMind iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: client
    environment:
      node: 22
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -project App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            build
    artifacts:
      - client/ios/App/build/**/*

  clearmind-android:
    name: ClearMind Android
    max_build_duration: 60
    instance_type: linux_x2
    working_directory: client
    environment:
      node: 22
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - client/android/app/build/outputs/apk/**/*.apk
